---
title: "Useful Apps for Learning Korean"
date: "2024-11-16"
categories: ["languages", "korean", "korea"]
comments: false
version: 1.0
---

These are apps that I've found useful for learning Korean while living in Korea,
in no particular order. Many of these will apply to various languages, not just Korean.
Please let me know if I missed any good ones!

Also, note that there is no "one best app". Learning a language requires
using multiple different resources.

I'm in the process of writing a recommended curriculum.

## Essential

### Youtube | 유튜브
If you had to have 1 app for learning, youtube is probably the ultimate choice.
For beginners, there are incredible channels such as:

- [Learn Korean with GO! Billy Korean](https://www.youtube.com/@GoBillyKorean)
- [Prof. Yoon's Korean Language Class](https://www.youtube.com/@ProfYoonsKoreanLanguageClass)

For intermediate and onwards you have, well... native content!
Native Content is crucial to learning any language to an advanced degree, and with youtube
you can find videos on pretty much any topic that interests you.

Tip 1: Add "자막" (subtitle) / 한글자막 (korean subtitles) to your searches.

Tip 2: Search a Korean word + "입문" (introduction) or "입문자" (pupil, learner) on a topic you like.

Tip 3: Make a separate youtube account and *only* watch native-made content on it,
so the algorithm learns to recommend that.

### Naver Dictionary | 네이버 사전
I think this one speaks for itself.
You can save and re-arrange dictionaries, so I've set it up like so:

- Korean-English dictionary: definitions in English
- 국어사전: defintions in Korean
- 한자사전: Hanja definitions
- Papapgo: I have the app installed but it's a convenient link.

If you make a Naver account, you can save words to wordlists.

[iOS App Store](https://apps.apple.com/us/app/naver-dictionary/id673085116)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.nhn.android.naverdic&hl=en-US)
| [Website](https://en.dict.naver.com/#/main)

### Naver Papago | 네이버  파파고
For daily life in Korea, the camera feature might be the most important one here.

I find Papago's Korean <-> English translations to be way more natural than Google Translate.

Make sure to download your languages for offline use!!!

[iOS App Store](https://apps.apple.com/us/app/naver-papago-ai-translator/id1147874819)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.naver.labs.translator&hl=en_US)
| [Website](https://papago.naver.com)

## Media

### Laftel
Recommended for intermediate learners and higher, Laftel is an anime streaming service,
with titles either dubbed or subtitled in Korean.
Basically the CrunchyRoll of Korea. \$10 per month.

For me, this is worthwhile because I don't like dramas.
Watching Dragon Ball and Bobobo-bo Bo-bobo dubbed in Korean is something, let me tell ya.

One downside is it seems you can only select the korean dub with no subtitles
or native audio with korean subtitles, but not both the korean dubbing with korean subtitles.

::: {.callout-note}
Laftel's only accessible inside of Korea and requires a Korean bank account.
:::

Hot Tip: Find a good Korean friend and ask them to help make an account for you.

[iOS App Store](https://apps.apple.com/th/app/laftel-watch-love-anime/id6447545713)
| [Google Play Store](https://play.google.com/store/apps/details?id=net.laftel.global&hl=en_US)
| [Website](https://laftel.net/)

### Netflix, Disney+, etc
For Netflix,
You can use [uNoGS.com](https://unogs.com/) to filter titles by
audio languages and subtitle languages offered.

::: {.callout-note}
The available shows will differ by country.
On a completely unrelated note, VPNs like Mullvad and NordVPN are useful for changing your displayed geographic location.
:::

## Vocabulary &amp; Spaced Repetition
Getting to 3k, 5k, and 8k learned words as soon as possible is paramount.

Roughly speaking, 3-5k words will let you have basic daily life conversations,
and 8k words is the threshold for interacting with more advanced native content
without burning out.

### Anki
In my opinion, this is the best spaced repetition flashcards app of all time.
The android and desktop apps are free, and the iOS app is a one time purchase of \$25.

I assure you the price is highly worth it given the value it provides.
This is the only way the developer makes money, and I'm more than happy to pay
considering how many hours I've used Anki for.

::: {.callout-warning}
Please be aware of copycats like AnkiPro and AnkiApp that are NOT related to the original Anki.
When in doubt, refer to the [Official Website](https://apps.ankiweb.net).
:::

[iOS App Store](https://apps.apple.com/us/app/ankimobile-flashcards/id373493387)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.ichi2.anki)
| [Website](https://apps.ankiweb.net/)

### Migaku
Migaku is both a chrome extension and a mobile flashcards app. It costs \$9 per month or \$87 per year.

It works with media sites like Netflix, Youtube, and Disney+, as well as regular sites.
It parses the subtitles and you can easily save words to anki/migaku flash cards.

The downside is you need to watch media with your laptop, which doesn't work for phone/tablet users.

[iOS App Store](https://apps.apple.com/us/app/migaku-really-learn-languages/id1664096855)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.migaku.android&hl=en_US)
| [Website](https://migaku.com/)

## Speaking &amp; Pronunciation

### Pimsleur
Pimsleur has amazing value for beginners, which tapers off as you reach intermediate and higher.
Each session is 30 minutes and they build on one another.
I highly recommend doing 3+ units before visiting Korea.

I recommend pairing pimsleur with:

- knocking out mindless house chores like washing the dishes
- driving

Hot Tip: If you commute to work, putting on Pimsleur or another app is an easy "hack" to get in more practice.

The pricing is as follows:

- Premium is \$19.95 per month and gives you access to 1 language
- All Access is \$20.95 per month and gives access to all languages
- All Access paid annually is \$164.95 per year, or roughly a 36% discount

[iOS App Store](https://apps.apple.com/us/app/pimsleur-language-learning/id1405735469)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.simonandschuster.pimsleur.unified.android&hl=en-US)
| [Website](https://www.pimsleur.com/)

### Glossika

If Pimsleur is great for beginners, Glossika is great for low to upper-intermediate learners.
Glossika was originally a modern version of Pimsleur (which was originally a set of audio recordings),
before Pimsleur themselves modernized.

While Pimsleur has structured units, Glossika is more of a collection of sentences with audio.
The pricing is as follows:

* Free for these languages: Catalan, Gaelic, Hakka (Sixian), Hakka (Hailu), Kurdish (Sorani), Manx, Welsh, Taiwanese, Wenzhounese
* Basic is \$16.99 per month (or \$160 paid annually, a 19% discount), and gives you access to 1 language. You can change your language once every 30 days.
* Pro is \$30.99 per month (\$300 paid annually, a 19% discount), and gives you access to every language.

::: {.callout-note }
I subscribed to pro for 1 year, and the next year I got to renew it for half off (\$150).
:::

Tip 1: If you're comfortable with the sentences in your target language, disable the english audio.
It'll speed up practicing by quite a lot.

Tip 2: Shorted the pause delay as much as you're comfortable with.
The faster repetitions go, the sooner you'll be done with Glossika for the day,
and the less likely you'll get burned out.

[iOS App Store](https://apps.apple.com/us/app/glossika-language-learning/id1597902556)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.glossika.ai&hl=en_US)
| [Website](https://ai.glossika.com/)

## Social

### Discord
Discord is the best social app by far. There are language learning servers,
like [Let's Learn Korean!](https://discord.gg/e3H9Pde), but once your profiency is good enough
you can hop into any native-speaking server.

If you like games, a gaming discord in your target language is an excellent way to naturally
converse in that language and make friends.
I far prefer this to the artificiality of language exchanges.

Hot Tip: Vet your servers carefully. Your experience will be particular to whatever server you end up joining.

[iOS App Store](https://apps.apple.com/us/app/discord-talk-play-hang-out/id985746746)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.discord&hl=en_US)
| [Website](https://discord.com/)

### HelloTalk
HelloTalk is essentially a social media site for language learners.
For Korean, you'll see posts written by Korean learners as well as native
Korean speakers who are learning English. It also supports calling.

People can give precise line by line feedback thanks to the built-in editing tools.
Of course it's expected you'll give corrections as well.

If you find the right people this can be a great tool; I had a friend who I'd swap a journal entry with each week.

For women, I hear that men often try to use HelloTalk as a dating website,
so it may not be as worthwhile.

[iOS App Store](https://apps.apple.com/us/app/hellotalk-language-learning/id557130558)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.hellotalk&hl=en_US)
| [Website](https://www.hellotalk.com/)

### Hilokal
Similar to HelloTalk, but only for 1:1 calls or group channels.
For 1:1 calls you can select "Free Talking" or do a "Role Play" of e.g. doing a Hotel check in.

I haven't used this much myself, but I've heard good things from my friends about it.

[iOS App Store](https://apps.apple.com/us/app/hilokal-language-exchange-app/id1537500613)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.hilokal&hl=en_US)
| [Website](https://www.hilokal.com/en)

### Meetup
This lets you find or organize meetup groups.
Although you need to pay for the Pro plan to be able to make groups and host events.

In Seoul there are *plenty* of language exchanges.
The trick is finding a group with lots of Koreans, as most of them are foreigner filled.

[iOS App Store](https://apps.apple.com/us/app/meetup-social-events-groups/id375990038)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.meetup&hl=en_US)
| [Website](https://www.meetup.com/)

### 소모임
Like Meetup but pretty much only Koreans. Needs a valid Korean phone number and is in Korean only.

[iOS App Store](https://apps.apple.com/kr/app/%EC%86%8C%EB%AA%A8%EC%9E%84/id582910479)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.friendscube.somoim&hl=ko)
| [Website](https://www.meetup.com/)

## Reading

### Naver Webtoon | 네이버 웹툰
If Japan has manga, Korea has webtoons.

[iOS App Store](https://apps.apple.com/us/app/webtoon-kr-%EB%84%A4%EC%9D%B4%EB%B2%84-%EC%9B%B9%ED%88%B0/id315795555)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.nhn.android.webtoon&hl=en_US)
| [Website](https://comic.naver.com/index)

### Ridi Books | 리디
You can purchase and download webtoons and translated manga.
I've been reading *Dragon Ball*, *Hunter X Hunter*, *One Piece*, and *Battle Angel: Alita*.

[iOS App Store](https://apps.apple.com/us/app/%EB%A6%AC%EB%94%94-%EC%9B%B9%ED%88%B0-%EB%A7%8C%ED%99%94-%EC%9B%B9%EC%86%8C%EC%84%A4-%EC%A0%84%EC%9E%90%EC%B1%85-%EB%AA%A8%EB%91%90-%EC%97%AC%EA%B8%B0%EC%97%90/id338813698)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.initialcoms.ridi&hl=en_US&pli=1)
| [Website](https://ridibooks.com/webtoon/recommendation)

## Audio

### Apple Podcasts
Personally, this is my favorite podcasts app.
I'm waiting for Apple to add automatic transcription support for Korean.

[iOS App Store](https://apps.apple.com/us/app/apple-podcasts/id525463029)

### Naver Audioclip | 네이버 오디오클립
Podcasts and audiobooks.

[iOS App Store](https://apps.apple.com/us/app/%EC%98%A4%EB%94%94%EC%98%A4%ED%81%B4%EB%A6%BD-audioclip/id1192635213)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.naver.naveraudio&hl=ko)
| [Website](https://audioclip.naver.com/)

### Podbbang | 팟빵
Podcasts and audiobooks in Korean.

[iOS App Store](https://apps.apple.com/us/app/%ED%8C%9F%EB%B9%B5/id612769954)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.makeshop.podbbang&hl=ko)
| [Website](https://www.podbbang.com/)

### 밀리의서재
A large collection of Korean books with human and TTS (Text To Speech) AI narrators.

Hot Tip: If you go to a Kyobo Books in Seoul, you might be able to find a
physical version of whatever you're listening to.

[iOS App Store](https://apps.apple.com/kr/app/%EB%B0%80%EB%A6%AC%EC%9D%98-%EC%84%9C%EC%9E%AC/id1213788923)
| [Google Play Store](https://play.google.com/store/apps/details?id=kr.co.millie.millieshelf&hl=en-US)
| [Website](https://www.millie.co.kr/)

### Storytel
Audiobooks in various languages. It seems books are region-locked, so this might not be useful outside of Korea.

[iOS App Store](https://apps.apple.com/us/app/storytel-audiobooks-library/id348177651)
| [Google Play Store](https://play.google.com/store/apps/details?id=grit.storytel.app&hl=en_US)

## Misc

### Naver | 네이버
It's the Google of Korea. There's stuff on there that isn't found by Google.

Hot Tip: It's worth it to make a Naver account to get access to more features in Naver Dictionary/Maps/Audioclip etc.

[iOS App Store](https://apps.apple.com/us/app/%EB%84%A4%EC%9D%B4%EB%B2%84-naver/id393499958)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.nhn.android.search&hl=en_US)
| [Website](https://naver.com)

### ChatGPT (for practicing Output)
It's important to practice output when learning any language.
It's better to do this with native speakers, but having mock conversations
from your phone at any hour is pretty handy.

The downside is LLMs are absolutely terrible for the environment.

[iOS App Store](https://apps.apple.com/us/app/chatgpt/id6448311069)
| [Google Play Store](https://play.google.com/store/apps/details?id=com.openai.chatgpt&hl=en_US)
| [Website](https://chatgpt.com/)

## NOT RECOMMENDED Apps

### Duolingo 👎
Duolingo was never good for CJK languages (Chinese, Japanese, Korean), and they're
reportedly working more with AI instead of native speakers.

If you only have ~15-20 mins, it's a far better use of your time to do Anki, Migaku, Pimsleur, Glossika, etc.

### ChatGPT (for knowledge questions) 👎
ChatGPT is a text generator that can't actually reason, and therefore doesn't know when it's wrong.
Sometimes it's right, but it's frequently wrong, and both appear the same unless you're
already knowledgeable about that topic.

I think un-learning incorrect information from slop is more work than learning correct information in the first place.
This is my "old man yells at cloud" moment but there is *so much information* available online, for free, for most languages.
Content that has been made by humans with intent.
