---
title: "Notes on Bluesky: Feeds"
date: "2024-11-17"
tags: ["social media", "bluesky"]
description: "Custom feeds are a genius concept that make social media palatable again."
---

I'll admit, when I first joined Bluesky I didn't
give too much thought to the idea of custom feeds.
But now I can't see myself going back.

One problem of a user network like Twitter or Tiktok growing is sifting
through the noise and finding meaningful content.

On Twitter, we were forced to choose between **THE ALGORITHM**,
or a reverse chronological timeline of everyone we follow.

To restate that: we were forced to choose between an algorithm that propped up
rage-bait and stupid shit that led to people bickering and dunking on one another,
or a time sensitive feed cluttered by That One Person Who Posts 1,000 Tweets Every Day.

Custom feeds that you can subscribe to completely sidestep these issues.
Here are some I enjoy:

## Follower-based

### [OnlyPosts](https://bsky.app/profile/skyfeed.xyz/feed/only-posts)
Only posts from people you follow without reposts and replies.

### [Mutuals](https://bsky.app/profile/skyfeed.xyz/feed/mutuals)
Posts from people who follow you back.

### [The 'Gram'](https://bsky.app/profile/why.bsky.team/feed/followpics)
Only pictures posted by people you follow.

## Discovery

### [Catch Up](https://bsky.app/profile/skyfeed.xyz/feed/catch-up)
The most popular posts in the last 24 hours.

### [Likes of Likes](https://bsky.app/profile/so-asano.com/feed/likes-of-likes)
A discovery feed of liked posts by the people whose posts you liked.
There's also the [default Discover feed](https://bsky.app/profile/bsky.app/feed/whats-hot),
made by the bluesky team.

## Niches - language, emoji, tag, and/or keyword-based

### [Filmsky](https://bsky.app/profile/did:plc:2hwwem55ce6djnk6bn62cstr/feed/aaaotdzmoni2q)
A feed for film discussion, showing posts that have the film projector emoji 📽️.

### [FGCSKY](https://bsky.app/profile/experimilk.bsky.social/feed/aaagi35wn2qfq)
A feed for fighting games discussion, drawing on specific keywords, tags, and the 💪🕹️ emoji.

### [Brasil Supercluster](https://bsky.app/profile/jaz.bsky.social/feed/cl-brasil)
Posts from people in the Brasil Supercluster.

---

There are so many feeds - find one that suits your tastes at [bsky.app/feeds](https://bsky.app/feeds)!
