---

project:
  type: website

  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render: ["*.qmd", "*.md"]
  resources:
    - "static/*"

pagetitle: " {{< meta title >}} | Andrew Zah"

website:
  title: "Andrew Zah | 자준재"
  description: ""
  site-url: 'https://andrewzah.com'
  open-graph: true
  bread-crumbs: true
  page-navigation: true
  favicon: ./static/favicon.ico

  repo-url: 'https://github.com/andrewzah/com.andrewzah'
  issue-url: 'https://github.com/andrewzah/com.andrewzah/issues'
  repo-subdir: 'src'
  repo-branch: 'master'
  repo-link-target: '_blank'
  repo-actions: [source, issue]

  page-footer: |
    <script data-goatcounter="https://stats.andrewzah.com/count"
        async src="//stats.andrewzah.com/count.js"></script>

  navbar:
    right:
      - href: posts.qmd
        text: Posts
      - href: reviews.qmd
        text: Reviews
      - href: now.qmd
        text: Now
      - sidebar:goodies
      #- href: "/gallery/cats/index.html"
      #  text: Cats

  sidebar:
    - id: goodies
      title: "Goodies"
      contents:
        - "./gallery/cats/index.qmd"
        - "./friends.qmd"
        - href: "/static/resume-andrew-zah.pdf"
          text: Resume

format:
  html:
    theme:
      light:
        - cosmo
      dark:
        - superhero
    toc: true
    grid:
      body-width: 900px
    code-link: true
    anchor-sections: true
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
