baseURL = "https://andrewzah.com/"
languageCode = "en-us"
theme = "zah"
summaryLength = 15
canonifyUrls = true
toc = true
destination = "./public"
title = "Andrew Zah's Site"
titleCaseStyle = 'none'

[params.author]
  name = "Andrew Zah"
  email = "zah@andrewzah.com"

[taxonomies]
  tag = 'tags'
  series = 'series'

[markup]
  [markup.highlight]
    # abap, autumn, github
    # https://gohugo.io/quick-reference/syntax-highlighting-styles/#github
    style = 'github'
    lineNos = 'false'
    #lineNumbersInTable = 'true'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "about/"

  [[menu.main]]
    identifier = "cats"
    name = "cats"
    url = "cats/"

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "posts/"

  [[menu.main]]
    identifier = "reviews"
    name = "reviews"
    url = "reviews/"

# symbols
# sym_neutral1 = "&#8857;"
# sym_neutral = "&#183;"
# sym_darr = "&#x1F86B;"
# sym_rarr = "&#x1F86A;"
# sym_uarr = "&#x1F869;"
# sym_larr = "&#x1F868;"
# sym_drarr = "&#x1F86E;"
# sym_dlarr = "&#x1F86F;"
# sym_urarr = "\u2191"
# sym_ularr = "\u2196"
# sym_clarr = "\u27FB"
# sym_cdarr = "\u21A7"
